### ISSUE TITLE
BindableSpinner and Enumerable.Range

### ISSUE THREAD

**Issue by snipervld** [Julien-Mialon/StormXamarin#2]
Hello. I attach project with this issue. In this project comment in MockVM class tells how to avoid this issue. 
And question: Is BindableSpinner works with IEnumerable<T> (in particaular with lazy collection)?
https://onedrive.live.com/redir?resid=BE878B196C95461B!1024&authkey=!AE2nRV4PFWzI7N8&ithint=file%2crar

Thanks

**Comment by Julien-Mialon** [comment]
Hello,

Your question is relative to your issue in fact, BindableSpinner himself is just an extended base android Spinner with the CurrentItem property in order to easily retrieve the selected item with binding.
The main problem come from adapter system used by Android, adapter need to know the number of element to display and be able to access any element in the collection. 
Because of this, adapters can only accept IList implementation (in order to have Count property and [] accesor). I just release a new version of Android and Android support package where IEnumerable is supported (if you bind to IEnumerable, your IEnumerable will be enumerated and turned into IList) but will not support lazy collection (like if you want to generate all even number using a yield statement in a for loop, it will enumerate all before displaying your view). It's just a fix for now since it should have been supported earlier.

I will try to create an implementation of Adapter based on CursorAdapter in order to be able to use lazy loading but it will be in a future release (probably later this week). I will post news here on this as soon as it's available.

**Comment by snipervld** [comment]
Thank you for response! Can you also add BindableListView (or ListBox)?

**Comment by Julien-Mialon** [comment]
Hello,

Implementing BindableListView could be easily done yes so I could do it once lazy adapter will be good.
But if you want to implement other controls, I'll be happy to integrate them in the framework next, Pull Request are well appreciated ;)

**Comment by Julien-Mialon** [comment]
Just to give you an update, this feature will be available by the end of day (GMT time)

**Comment by Julien-Mialon** [comment]
It's now available in version 1.2.20. Finally, using CursorAdapter was a mistake, it's so slow !
Instead, I create a custom implementation of IList to wrap IEnumerable and enumerate element just when it's needed. So BindableAdapter automatically choose if your collection will be wrapped into this custom IList and thanks to this, everything remain transparent for developer.
